---
name: agent-core-ci

on:
  push:
    branches: [ main, 'feat/**' ]
    paths:
      - '**.py'
      - 'services/**'
      - '.github/workflows/**'
      - 'openapi.snapshot.json'
  pull_request:
    branches: [ main ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  validate:
    runs-on: ubuntu-latest
    timeout-minutes: 45
    concurrency:
      group: validate-${{ github.ref }}
      cancel-in-progress: true
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install dependencies (retry)
        run: |
          n=0
          until [ $n -ge 3 ]; do
            python -m pip install --upgrade pip && pip install -r requirements-dev.txt && break
            n=$((n+1)); echo "retry $n/3"; sleep 30
          done

  integration:
    needs: [validate]
    runs-on: ubuntu-latest
    timeout-minutes: 45

  contract_check:
    needs: [validate]
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@v4
      - name: Generate current OpenAPI spec
        run: |
          python -c "import json, pathlib; \
          from services.agent_runner.src.main import app; \
          current_spec = app.openapi(); \
          pathlib.Path('openapi.current.json').write_text(\
          json.dumps(current_spec, indent=2), encoding='utf-8')"
      - name: Upload OpenAPI current spec as artifact
        uses: actions/upload-artifact@v4
        with:
          name: openapi-current-${{ github.run_id }}
          path: openapi.current.json
      - name: Compare with snapshot
        run: diff -u openapi.snapshot.json openapi.current.json
