name: agent-core-ci

on:
  pull_request:
    paths:
      - 'services/**'
      - 'requirements-dev.txt'
      - '.github/workflows/agent-core-ci.yml'

jobs:
  validate:
    runs-on: ubuntu-latest
    env:
      PYTHONPATH: ${{ github.workspace }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python 3.12
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install dev dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements-dev.txt

      - name: Debug env before tests
        run: |
          echo "PYTHONPATH=$PYTHONPATH"
          python -V
          which python
          python -m pip show pytest || true
          python - <<'PY'
import sys
print("sys.path[0:6] =", sys.path[:6])
PY

      - name: Run tests
        run: python -m pytest -q services
