name: agent-core-smoke

on: [pull_request, push]

jobs:
  validate-agent-core:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # --- START CORRECCIÓN CI: INSTALACIÓN DE DEPENDENCIAS Y PYTHON_PATH ---
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"
          
      - name: Upgrade pip and install agent-core deps
        run: |
          python -m pip install --upgrade pip
          # Instala las dependencias necesarias: requests, google-genai, pytest
          python -m pip install -r services/agent-core/requirements.txt
        env:
          PIP_CACHE_DIR: ${{ runner.temp }}/pip-cache

      - name: Ensure PYTHONPATH includes repo root
        # Esto permite que los tests y main.py encuentren los módulos del repo (e.g., services.agent_core.src...)
        run: echo "PYTHONPATH=$(pwd)" >> $GITHUB_ENV
      # --- END CORRECCIÓN CI ---

      - name: Validate OpenAPI Contract
        run: npx -y @apidevtools/swagger-cli validate services/agent-runner/openapi/openapi.json
      
      - name: Run unit tests for agent-core
        # Ahora el entorno tiene las dependencias y el PYTHONPATH correcto
        run: pytest -q services/agent-core/tests
        
      # El smoke test E2E (arrancar uvicorn y .ci/smoke-agent-runner.sh) iría aquí para la prueba completa
