name: agent-core-ci

on:
  pull_request:
    paths:
      - 'services/**'
      - 'requirements-dev.txt'
      - '.github/workflows/agent-core-ci.yml'
  push:
    branches:
      - main

jobs:
  validate:
    runs-on: ubuntu-latest
    env:
      PYTHONPATH: ${{ github.workspace }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python 3.12
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install dev dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements-dev.txt
      - name: Debug env before tests
        run: |
          echo "PYTHONPATH=$PYTHONPATH"
          python -V
          which python
          python -m pip show pytest || true
          python -c "import sys; print('sys.path[0:6]=', sys.path[:6])"
      - name: Run unit tests
        run: python -m pytest -q services/agent_core/tests

  integration:
    # Este job SOLO se ejecuta si el job 'validate' (unit tests) pasa primero.
    needs: validate 
    runs-on: ubuntu-latest
    env:
      PYTHONPATH: ${{ github.workspace }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python 3.12
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install dev dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements-dev.txt
      
      - name: Run integration tests (agent_runner)
        run: |
          echo "Running integration tests for agent_runner"
          python -c "import sys; print('PYTHONPATH=', sys.path[0])"
          # Comando clave: Ejecuta pytest solo en la carpeta de tests de agent_runner
          python -m pytest -q services/agent_runner/tests
        continue-on-error: false # ¡Si falla, detiene el build!

      - name: Upload pytest logs on failure
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: pytest-logs-integration
          path: .pytest_cache || ./htmlcov || ./logs || ./ --if-exists
