---
name: agent-core-ci

on:
  workflow_dispatch: true
  pull_request:
    paths:
      - 'services/**'
      - 'requirements-dev.txt'
      - '.github/workflows/agent-core-ci.yml'
  push:
    branches:
      - main

jobs:
  validate:
    runs-on: ubuntu-latest
    env:
      PYTHONPATH: ${{ github.workspace }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: '3.12'
      - run: |
          python -m pip install --upgrade pip && \
          python -m pip install -r requirements-dev.txt
      - run: python -m pytest -q services/agent_core/tests

  integration:
    needs: validate
    runs-on: ubuntu-latest
    env:
      PYTHONPATH: ${{ github.workspace }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: '3.12'
      - run: |
          python -m pip install --upgrade pip && \
          python -m pip install -r requirements-dev.txt
      - run: python -m pytest -q services/agent_runner/tests

  contract_check:
    needs: [validate, integration]
    runs-on: ubuntu-latest
    env:
      PYTHONPATH: ${{ github.workspace }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: '3.12'
      - run: |
          python -m pip install --upgrade pip && \
          python -m pip install -r requirements-dev.txt
      - name: Check for snapshot file
        run: |
          if [ ! -f openapi.snapshot.json ]; then \
          echo "❌ Falta openapi.snapshot.json."; \
          echo "Debes generarlo o agregarlo al repo."; \
          exit 1
      - name: Generate current OpenAPI spec
        run: |
          python -c "import json, pathlib; \
          from services.agent_runner.src.main import app; \
          current_spec = app.openapi(); \
          pathlib.Path('openapi.current.json').write_text(\
          json.dumps(current_spec, indent=2), encoding='utf-8')"
      - name: Compare OpenAPI specs
        run: |
          if diff openapi.snapshot.json openapi.current.json; then \
          echo "✅ OpenAPI contract matches snapshot."; \
          else \
          echo "❌ OpenAPI contract ha cambiado."; \
          echo "Verifica los cambios."; \
          exit 1
