---
name: agent-core-ci

on:
  push:
    branches: [main, "feat/**", "chore/**", "fix/**"]
    paths:
      - "**.py"
      - "services/**"
      - ".github/workflows/**"
      - "openapi.snapshot.json"
  pull_request:
    branches: [main]

concurrency:
  group: "${{ github.workflow }}-${{ github.ref }}"
  cancel-in-progress: true

jobs:
  validate:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    concurrency:
      group: "validate-${{ github.ref }}"
      cancel-in-progress: true
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: "pip-${{ runner.os }}-${{ hashFiles('requirements-dev.txt') }}"
          restore-keys: |
            pip-${{ runner.os }}-
      - name: Install dependencies (retry)
        shell: bash
        run: |
          set -e
          n=0
          until [ $n -ge 3 ]; do
            python -m pip install --upgrade pip && \
            pip install -r requirements-dev.txt && \
            pip install -e services/agent_runner && break
            n=$((n+1)); echo "retry $n/3"; sleep 20
          done
      - name: Run tests (tox)
        run: |
          pip install tox
          tox -e py311

  integration:
    needs: [validate]
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@v4
      # añade aquí tus pasos de integración reales

  contract_check:
    needs: [validate]
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v4
      - name: Generate current OpenAPI spec
        shell: bash
        run: |
          python - <<'PY'
          import json, pathlib
          from services.agent_runner.src.main import app
          pathlib.Path('openapi.current.json').write_text(json.dumps(app.openapi(), indent=2), encoding='utf-8')
          PY
      - name: Upload OpenAPI current spec as artifact
        uses: actions/upload-artifact@v4
        with:
          name: openapi-current-${{ github.run_id }}
          path: openapi.current.json
      - name: Compare with snapshot
        shell: bash
        run: diff -u openapi.snapshot.json openapi.current.json
