name: agent-core-ci

on:
  workflow_dispatch:
  pull_request:
    paths:
      - 'services/**'
      - 'requirements-dev.txt'
      - '.github/workflows/agent-core-ci.yml'
  push:
    branches:
      - main

jobs:
  validate:
    runs-on: ubuntu-latest
    env:
      PYTHONPATH: ${{ github.workspace }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: '3.12'
      - run: python -m pip install --upgrade pip && python -m pip install -r requirements-dev.txt
      - run: python -m pytest -q services/agent_core/tests

  integration:
    needs: validate
    runs-on: ubuntu-latest
    env:
      PYTHONPATH: ${{ github.workspace }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: '3.12'
      - run: python -m pip install --upgrade pip && python -m pip install -r requirements-dev.txt
      - run: python -m pytest -q services/agent_runner/tests

  contract_check:
    needs: [validate, integration]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: '3.12'
      - run: python -m pip install -r requirements-dev.txt
      - name: Debug sys.path
        run: |
          python -c "import sys; print(sys.path)"
      - name: Check file existence
        run: |
          ls -l services/agent-runner/openapi/
      - name: Generate current OpenAPI spec
        run: |
          python -m services.agent_runner.src.main > openapi.current.json
      - name: Compare OpenAPI specs
        run: diff services/agent-runner/openapi/openapi.snapshot.json openapi.current.json
      - if: success()
        run: echo "✅ OpenAPI contract matches snapshot."
