---
name: agent-core-ci

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  workflow_dispatch:
  pull_request:
    paths:
      - 'services/**'
      - 'requirements-dev.txt'
      - '.github/workflows/agent-core-ci.yml'
  push:
    branches:
      - main

jobs:
  validate:
    runs-on: ubuntu-latest
    env:
      PYTHONPATH: ${{ github.workspace }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: '3.12'
      - run: |
          python -m pip install --upgrade pip && \
          python -m pip install -r requirements-dev.txt
      - run: python -m pytest -q services/agent_core/tests

  integration:
    needs: validate
    runs-on: ubuntu-latest
    env:
      PYTHONPATH: ${{ github.workspace }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: '3.12'
      - run: |
          python -m pip install --upgrade pip && \
          python -m pip install -r requirements-dev.txt
      - run: python -m pytest -q services/agent_runner/tests

  contract_check:
    needs: [validate, integration]
    runs-on: ubuntu-latest
    env:
      PYTHONPATH: ${{ github.workspace }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: '3.12'
      - run: |
          python -m pip install --upgrade pip && \
          python -m pip install -r requirements-dev.txt
      - name: Generate current OpenAPI spec
        run: |
          python -c "import json, pathlib; \
          from services.agent_runner.src.main import app; \
          current_spec = app.openapi(); \
          pathlib.Path('openapi.current.json').write_text(\
          json.dumps(current_spec, indent=2), encoding='utf-8')"
      - name: Upload OpenAPI current spec as artifact
        uses: actions/upload-artifact@v4
        with:
          name: openapi-current-${{ github.run_id }}
          path: openapi.current.json
      - name: Compare contract
        run: diff openapi.snapshot.json openapi.current.json
      - if: success()
        run: echo "✅ OpenAPI contract matches snapshot."
