name: agent-core-ci

on:
  pull_request:
    paths:
      - 'services/agent-core/**'
      - 'services/agent-runner/**'
      - '.github/workflows/agent-core-ci.yml'

jobs:
  validate-agent-core:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Upgrade pip and install agent-core deps
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r services/agent-core/requirements.txt
        env:
          PIP_CACHE_DIR: ${{ runner.temp }}/pip-cache

      - name: Ensure PYTHONPATH includes repo root
        run: echo "PYTHONPATH=$(pwd)" >> $GITHUB_ENV

      - name: Debug: list installed packages and python info
        run: |
          python -V
          which python
          python -m pip list
          python -c "import sys; print('sys.path first entries:', sys.path[:6])"

      - name: Validate OpenAPI
        run: |
          npx -y @apidevtools/swagger-cli validate services/agent-runner/openapi/openapi.json || echo "OpenAPI validate failed (non-blocking here)"

      - name: Run unit tests for agent-core
        run: pytest -q services/agent-core/tests
