---
name: Cleanup Old Artifacts

on:
  schedule:
    # Run daily at 2 AM UTC
    - cron: '0 2 * * *'
  workflow_dispatch:

jobs:
  cleanup:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Cleanup old artifacts
        uses: actions/github-script@v7
        with:
          script: |
            const repo = context.repo;
            const retentionDays = 30;
            const cutoffDate = new Date();
            cutoffDate.setDate(cutoffDate.getDate() - retentionDays);
            
            console.log(`Cleaning up artifacts older than ${retentionDays} days (before ${cutoffDate.toISOString()})`);
            
            // Get all artifacts
            const artifacts = await github.rest.actions.listArtifactsForRepo({
              owner: repo.owner,
              repo: repo.repo,
              per_page: 100
            });
            
            let deletedCount = 0;
            for (const artifact of artifacts.data.artifacts) {
              const createdAt = new Date(artifact.created_at);
              if (createdAt < cutoffDate) {
                console.log(`Deleting artifact: ${artifact.name} (created: ${artifact.created_at})`);
                await github.rest.actions.deleteArtifact({
                  owner: repo.owner,
                  repo: repo.repo,
                  artifact_id: artifact.id
                });
                deletedCount++;
              }
            }
            
            console.log(`Cleanup complete. Deleted ${deletedCount} artifact(s).`);
