---
name: temp-dispatch

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Test Workflow Dispatch
        run: echo "Temporary workflow to test dispatch trigger."